debug_log: True

fxcm:
  token: "d128bbccc360344261da7f2b76d5bc55244a90ef"
  log_level: "error" 
  server_mode: "demo"
  log_file: "log.txt"
  order_amount: 100
  devises: "EUR/USD"
  period: "m5"
  number: 10000

prophet:
  predictions: 1
  changepoint: 0.001
  seasonality: 10.0

chart:
  parameters:
    begin: -5000
    end: -1

yfinance:
  tickers: "EURUSD=X"
  period: "1mo"
  interval: "5m"