debug_log: True

fxcm:
  token: "33ad2c2c73249386052bcdadd562591ef4140c18"
  log_level: "error" 
  server_mode: "demo"
  log_file: "log.txt"
  order_amount: 100
  mean_close_amount: 50
  devises: ['USD/JPY']
  period: "m5"
  number: 10000

prophet:
  predictions: 1
  changepoint: 0.001
  seasonality: 10.0

chart:
  parameters:
    begin: -5000
    end: -1

yfinance:
  tickers: "EURUSD=X"
  period: "1mo"
  interval: "5m"

trading:
  sleeping_time: 290
  process_timeout: 390