debug_log: True

fxcm:
  token: "eee8d79405eff525f40bd6f32fb2b650a701836c"
  log_level: "error" 
  server_mode: "demo"
  log_file: "log.txt"
  order_amount: 100
  devises: "EUR/USD"
  period: "m5"
  column_open: ['bidclose']

yahoo_finance:
  tickers: "EURUSD=X"
  period: "12d"
  interval: "5m"
  group_by: "ticker"
  auto_adjust: True
  threads: True
  proxy: None

prophet:
  predictions: 1
  changepoint: 0.001

chart:
  parameters:
    begin: -250
    end: -1