debug_log: True

fxcm:
  token: "9155abfb3e76e78942b6513f3e6a94e7d3ae05a6"
  log_level: "error" 
  server_mode: "demo"
  log_file: "log.txt"
  order_amount: 100
  mean_close_amount: 50
  devises: ['USD/JPY', 'EUR/USD']
  period: "m5"
  number: 10000

prophet:
  predictions: 1
  changepoint: 0.001
  seasonality: 10.0

chart:
  parameters:
    begin: -5000
    end: -1

yfinance:
  tickers: "EURUSD=X"
  period: "1mo"
  interval: "5m"

trading:
  sleeping_time: 295
  process_timeout: 295

binance:
  api_key: "9XFoJY6fqdSDXur0jwmkSLEYYPv7hzpnR418dVTPn1jn8UJN2dhzaN7XmhS3ibyx"
  secret_key: "cwoiKFmfY1felXIvLB3DiQqAr0i9ZVM8T9jgB9rrWKjj91uEWJRs7z6EVkpxzjgH"

elasticsearch:
  host:
  port: