debug_log: True

fxcm:
  token: "c544d10634d6e7fd606890de2aa10115c64a5eb6"
  log_level: "error" 
  server_mode: "demo"
  log_file: "log.txt"
  order_amount: 100
  mean_close_amount: 50
  devises: ['USD/JPY', 'GBP/USD', 'EUR/USD']
  period: "m5"
  number: 5000

prophet:
  predictions: 1
  changepoint: 0.001
  seasonality: 10.0

chart:
  parameters:
    begin: -5000
    end: -1

yfinance:
  tickers: "EURUSD=X"
  period: "1mo"
  interval: "5m"